version: 2.1
jobs:
  deploy:
    working_directory: ~/repo
    docker:
      - image: shaperid/node-aws-ci:latest
    environment:
      NODE_OPTIONS: --max_old_space_size=4096
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: Install deps
          command: yarn
      - run:
          name: Build application
          command: yarn build-release
      - run:
          name: Upload static
          command: aws s3 sync /home/circleci/repo/dist/ s3://widget.otechie.com/dist --delete --acl public-read

workflows:
  deploy:
    jobs:
      - deploy
